# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

_file_map = {

    "sales_copilot.baml": "class ObjectionHandler {\n  provider_id string\n  response string\n}\n\nclass MeetingScript {\n  provider_id string\n  script string\n}\n\nfunction GenerateObjectionHandler(provider_id: string, concern: string, kb_context: string) -> ObjectionHandler {\n  client \"google-ai/gemini-2.5-flash\"\n  prompt #\"\nYou are a Tempus Sales Copilot assistant.\nReturn a concise objection handler for provider {{ provider_id }}.\nConcern: {{ concern }}\nKB context: {{ kb_context }}\n\"#\n}\n\nfunction GenerateMeetingScript(provider_id: string, tumor_focus: string, kb_context: string) -> MeetingScript {\n  client \"google-ai/gemini-2.5-flash\"\n  prompt #\"\nYou are a Tempus Sales Copilot assistant.\nWrite a 30-second tailored meeting script for provider {{ provider_id }}.\nTumor focus: {{ tumor_focus }}\nKB context: {{ kb_context }}\n\"#\n}\n",
}

def get_baml_files():
    return _file_map