# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (2)
# #########################################################################

class MeetingScript(BaseModel):
    provider_id: typing.Optional[str] = None
    tumor_focus: typing.Optional[str] = None
    script: typing.Optional[str] = None
    citations: typing.List[str]
    confidence: typing.Optional[float] = None

class ObjectionHandler(BaseModel):
    provider_id: typing.Optional[str] = None
    concern: typing.Optional[str] = None
    response: typing.Optional[str] = None
    supporting_metrics: typing.List[str]
    citations: typing.List[str]
    confidence: typing.Optional[float] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
